baseURL = "https://newgrubstreet.com/"
buildDrafts = false
buildExpired = false
buildFuture = false
enableRobotsTXT = true
googleAnalytics = "UA-123-45"
languageCode = "en-us"
paginate = 5
theme = "hugo-PaperMod"
title = "New Grub Street"
[[menu.main]]
identifier = "Tags"
name = "Tags"
url = "/tags/"
weight = 4
[[menu.main]]
identifier = "Recommended Websites"
name = "Recommended Websites"
url = "/recommended-websites/"
weight = 3
[[menu.main]]
identifier = "Archive"
name = "Archive"
url = "/archive/"
weight = 2
[[menu.main]]
identifier = "Search"
name = "Search"
url = "/search/"
weight = 1
[[menu.main]]
identifier = "About"
name = "About"
url = "/about/"
weight = 5
[minify]
disableXML = true
minifyOutput = true
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
ShowReadingTime = true
ShowShareButtons = false
comments = false
defaultTheme = "light"
description = "Writing on books, film, and music"
disableSpecial1stPost = true
disableThemeToggle = true
env = "production"
hidemeta = false
images = ["<link or path of image for opengraph, twitter-cards>"]
showtoc = false
title = "New Grub Street"
tocopen = false
[params.assets]
apple_touch_icon = "/apple-touch-icon.png"
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "</favicon-32x32.png"
safari_pinned_tab = "<link / abs url>"
[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true
[params.fuseOpts]
distance = 1000
isCaseSensitive = false
keys = ["title", "permalink", "summary", "content"]
location = 0
minMatchCharLength = 0
shouldSort = true
threshold = 0.4
[params.label]
icon = "/apple-touch-icon.png"
iconHeight = 30
[params.profileMode]
enabled = false
imageHeight = 120
imageTitle = "my image"
imageUrl = "<img location>"
imageWidth = 120
title = "ExampleSite"
[[params.profileMode.buttons]]
name = "Posts"
url = "posts"
[[params.profileMode.buttons]]
name = "Tags"
url = "tags"
